# Generated by Django 4.1 on 2022-10-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_english_ans_maths_ans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay', models.TextField()),
                ('Quest', models.TextField()),
                ('op1', models.CharField(max_length=100)),
                ('op2', models.CharField(max_length=100)),
                ('op3', models.CharField(max_length=100)),
                ('op4', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='english',
            name='ans',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='maths',
            name='ans',
            field=models.CharField(max_length=100),
        ),
    ]
